---
- name: Install Nginx
  hosts: all
  become: true  # This allows Ansible to become root (sudo)

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      tags:
        - nginx

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - nginx

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx
      tags:
        - nginx

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded


